# Generated by Django 3.2.8 on 2021-10-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=250, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('preciocompra', models.FloatField(verbose_name='Precio de compra')),
                ('precioventa', models.FloatField(verbose_name='Precio de venta')),
                ('existencia', models.IntegerField(verbose_name='Existencia')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nit', models.CharField(max_length=250, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('empleados_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleados')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Infoventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('productos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
                ('ventas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventas')),
            ],
            options={
                'verbose_name': 'Infoventa',
                'verbose_name_plural': 'Infoventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('productos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
    ]
